import XCTest
@testable import RommioContract
@testable import RommioFoundation
@testable import RommioUI

final class SupportGroupingTests: XCTestCase {
    func testGroupedPlatformSectionsMirrorAndroidTaxonomy() {
        let resolver = PlatformControlProfileResolver()
        let sections = groupedPlatformSections(
            platforms: [
                PlatformDTO(id: 1, slug: "nes", name: "NES", fsSlug: "nes", romCount: 10),
                PlatformDTO(id: 2, slug: "psp", name: "PSP", fsSlug: "psp", romCount: 6),
                PlatformDTO(id: 3, slug: "ps2", name: "PS2", fsSlug: "ps2", romCount: 4),
            ],
            resolveProfile: resolver.resolve(platformSlug:)
        )

        XCTAssertEqual(sections.map(\.title), [
            "Touch-ready in app",
            "Controller play in app",
            "Not supported in app yet",
        ])
        XCTAssertEqual(sections[0].platforms.map(\.slug), ["nes"])
        XCTAssertEqual(sections[1].platforms.map(\.slug), ["psp"])
        XCTAssertEqual(sections[2].platforms.map(\.slug), ["ps2"])
    }

    func testGroupedRomSectionsKeepControllerAndUnsupportedSeparate() {
        let resolver = PlatformControlProfileResolver()
        let sections = groupedRomSections(
            roms: [
                RomDTO(id: 1, name: "Mario", platformName: "NES", platformSlug: "nes"),
                RomDTO(id: 2, name: "Lumines", platformName: "PSP", platformSlug: "psp"),
                RomDTO(id: 3, name: "Shadow", platformName: "PS2", platformSlug: "ps2"),
            ],
            context: .platformDetail,
            resolveProfile: resolver.resolve(platformSlug:)
        )

        XCTAssertEqual(sections.map { $0.supportTier }, [.touchSupported, .controllerSupported, .unsupported])
        XCTAssertEqual(sections[1].roms.map { $0.id }, [2])
        XCTAssertEqual(sections[2].roms.map { $0.id }, [3])
    }

    func testGroupedCollectionsMatchAndroidKinds() {
        let sections = groupedCollectionSections(collections: [
            RommCollectionDTO(kind: .regular, id: "1", name: "Favorites"),
            RommCollectionDTO(kind: .smart, id: "2", name: "Beaten"),
            RommCollectionDTO(kind: .virtual, id: "3", name: "Recently Added"),
        ])

        XCTAssertEqual(sections.map(\.title), ["My collections", "Smart collections", "Autogenerated"])
        XCTAssertEqual(sections[0].collections.map(\.name), ["Favorites"])
        XCTAssertEqual(sections[1].collections.map(\.name), ["Beaten"])
        XCTAssertEqual(sections[2].collections.map(\.name), ["Recently Added"])
    }
}
