package io.github.bandoracer.rommio.ui.screen.collections

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.lifecycle.viewmodel.initializer
import androidx.lifecycle.viewmodel.viewModelFactory
import io.github.bandoracer.rommio.AppContainer
import io.github.bandoracer.rommio.model.CollectionKind
import io.github.bandoracer.rommio.model.RommCollectionDto
import io.github.bandoracer.rommio.ui.component.CollectionSpotlightCard
import io.github.bandoracer.rommio.ui.component.EmptyStatePanel
import io.github.bandoracer.rommio.ui.component.FeaturePanel
import io.github.bandoracer.rommio.ui.component.LoadingSkeletonPanel
import io.github.bandoracer.rommio.ui.component.SectionHeader
import io.github.bandoracer.rommio.ui.screen.collectAsStateWithLifecycleCompat

@Composable
fun CollectionsScreen(
    container: AppContainer,
    imageBaseUrl: String?,
    onCollectionSelected: (RommCollectionDto) -> Unit,
) {
    val viewModel: CollectionsViewModel = viewModel(
        factory = viewModelFactory {
            initializer { CollectionsViewModel(container.repository) }
        },
    )
    val state by viewModel.uiState.collectAsStateWithLifecycleCompat()
    val sections = buildCollectionSections(state.collections)

    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 14.dp),
        verticalArrangement = Arrangement.spacedBy(14.dp),
    ) {
        item {
            FeaturePanel(
                title = "RomM collections",
                subtitle = "Collections are grouped by type so your own sets stay first, followed by smart and autogenerated groups from RomM.",
                badge = "Grouped by type",
                eyebrow = "Collections",
            ) {
                Text(
                    "The Android client shows manual, smart, and autogenerated collections separately instead of flattening them into one mixed list.",
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
        if (state.isLoading) {
            items(3) { LoadingSkeletonPanel(showArtwork = true, lines = 2) }
        }
        sections.forEach { section ->
            item(key = "section-${section.title}") {
                SectionHeader(
                    title = section.title,
                    meta = section.collections.size.toString(),
                    supportingText = section.supportingText,
                )
            }
            items(section.collections, key = { "${it.kind}:${it.id}" }) { collection ->
                CollectionSpotlightCard(
                    collection = collection,
                    imageBaseUrl = imageBaseUrl,
                    fallbackCoverUrls = state.collectionPreviewCoverUrls["${collection.kind}:${collection.id}"].orEmpty(),
                    onClick = { onCollectionSelected(collection) },
                )
            }
        }
        if (!state.isLoading && state.collections.isEmpty() && state.errorMessage == null) {
            item {
                EmptyStatePanel(
                    title = "No collections available",
                    subtitle = "This account is connected, but the server is not exposing any collections to the Android client right now.",
                    badge = "Remote empty",
                    supportingText = "Create collections on the server or switch to a profile that exposes manual, smart, or generated sets.",
                )
            }
        }
        state.errorMessage?.let { message ->
            item { Text(message, color = MaterialTheme.colorScheme.error) }
        }
    }
}

private data class CollectionSection(
    val title: String,
    val supportingText: String,
    val collections: List<RommCollectionDto>,
)

private fun buildCollectionSections(collections: List<RommCollectionDto>): List<CollectionSection> {
    val regular = collections.filter { it.kind == CollectionKind.REGULAR }
    val smart = collections.filter { it.kind == CollectionKind.SMART }
    val virtual = collections.filter { it.kind == CollectionKind.VIRTUAL }

    return listOf(
        CollectionSection(
            title = "My collections",
            supportingText = "Manual collections created and managed in RomM.",
            collections = regular,
        ),
        CollectionSection(
            title = "Smart collections",
            supportingText = "Rule-based groups maintained by RomM filters.",
            collections = smart,
        ),
        CollectionSection(
            title = "Autogenerated",
            supportingText = "Virtual collections generated by the server.",
            collections = virtual,
        ),
    ).filter { it.collections.isNotEmpty() }
}
